search_tweets_api:
  account_type: premium
  endpoint: https://api.twitter.com/1.1/tweets/search/fullarchive/EnvFull.json
  consumer_key: KzbAhJahqZ1oXLob5gik3Ay57
  consumer_secret: AC29573TUDWLyRfLKsHP8oyGGiVzwydPcQihI8a6hLYttYihUa
